### ISSUE TITLE
Failed to read large IndexedDB value

### ISSUE THREAD

**Issue by yingyuk** [piotr-cz/swr-idb-cache#12]
my users reported an issue where the "Failed to read large IndexedDB value" error caused the page to keep displaying '[Loading](https://github.com/piotr-cz/swr-idb-cache/blob/962db4708adaa3c56dfb5f07f84ed63b2cb15dba/README.md?plain=1#L56)'.

this was due to an IndexedDB read error, resulting in '[createCacheProvider.then](https://github.com/piotr-cz/swr-idb-cache/blob/962db4708adaa3c56dfb5f07f84ed63b2cb15dba/src/use-cache-provider.ts#L17) is not a function.'

the users' actual data stored isn't large, suggesting a browser error with no clear solution.

if we wrap [this code](https://github.com/piotr-cz/swr-idb-cache/blob/962db4708adaa3c56dfb5f07f84ed63b2cb15dba/src/cache-provider.ts#L45-L61) in a try-catch block, it can prevent the page from becoming unusable.

**Comment by piotr-cz** [comment]
Yeah, this might be a good idea.
Can you submit a pull request?
