### ISSUE TITLE
Could not find a declaration

### ISSUE THREAD

**Issue by KoBa4** [piotr-cz/swr-idb-cache#14]
Next.js 14
Typescript error

Could not find a declaration file for module `@piotr-cz/swr-idb-cache`.
`/path/to/project/node_modules/@piotr-cz/swr-idb-cache/dist/index.mjs` implicitly has an  any  type.

There are types at `/home/cova4/Projects/NodeJS/netflix-v2/node_modules/@piotr-cz/swr-idb-cache/dist/index.d.ts`, but this result could not be resolved when respecting package.json `exports`.

The `@piotr-cz/swr-idb-cache` library may need to update its package.json or typings.

**Comment by piotr-cz** [comment]
Do you have any idea how to fix this?

If the issue occurs only in VScode, try restarting TS Server (ctrl + shift + p > TypeScript: Restart TS Server)

**Comment by piotr-cz** [comment]
Seems that the `package.json` file should be updated like this: https://github.com/huozhi/bunchee?tab=readme-ov-file#typescript

**Comment by hcapp01** [comment]
this is the PR to fix this https://github.com/piotr-cz/swr-idb-cache/pull/16

**Comment by piotr-cz** [comment]
@KoBa4 Can you confirm that #16 fixed this issue?

**Comment by piotr-cz** [comment]
Fix released in [v1.0.3](https://github.com/piotr-cz/swr-idb-cache/releases/tag/v1.0.3)
