### ISSUE TITLE
Yarn install script is wrong

### ISSUE THREAD

**Issue by MakakWasTaken** [piotr-cz/swr-idb-cache#15]
The value under the installation section for yarn is wrong.

It should be 
`yarn add @piotr-cz/swr-idb-cache`
instead of
`yarn add @piotr-cz/@piotr-cz/swr-idb-cache`

**Comment by piotr-cz** [comment]
Thanks, fixed in [#7a9f176](https://github.com/piotr-cz/swr-idb-cache/commit/7a9f17642359517cdaaf326a4f696afdffedbfc3)
