### ISSUE TITLE
while initialize cache provider, it's unnecessary to render fallback component

### ISSUE THREAD

**Issue by siuming-qiu** [piotr-cz/swr-idb-cache#17]
```
// App.jsx
import { SWRConfig } from 'swr'
import { useCacheProvider } from '@piotr-cz/swr-idb-cache'

function App() {
  // Initialize
  const cacheProvider = useCacheProvider({
    dbName: 'my-app',
    storeName: 'swr-cache',
  })

  // it's unnecessary to render fallback component
  // swr will re-render after the provider initialized
  // if (!cacheProvider) {
  //  return <div>Initializing cache…</div>
  //}

  return (
    <SWRConfig value={{
      provider: cacheProvider,
    }}>
      <Dashboard />
    </SWRConfig>
  )
}
```

**Comment by piotr-cz** [comment]
I would say it's up to the developer how to handle situation when cache provider is getting ready.

What about changing the comment

```diff
- // Cache Provider is being initialized - render fallback component in the meantime
+ // Optional: Render fallback component while Cache provider is being initialized
  if (!cacheProvider) {
    return <div>Initializing cache…</div>
  }
```

**Comment by piotr-cz** [comment]
I've been thinking about this.

If you don't use fallback component or implement any other mechanism, SWR will use it's own default in-memory cache during package initialization and requests won't be saved into persistent cache.

So while it's not necessary to use fallback component, it makes very little sense to do so.

I have no idea how to rephrase the comment, so I'll leave it like it is.
If you have any suggestions, please add them here and I may reopen this issue.
