### ISSUE TITLE
Excuse me, how to modify the value stored in indexDB?

### ISSUE THREAD

**Issue by qiaogaolong** [piotr-cz/swr-idb-cache#6]
Excuse me, how to modify the value stored in indexDB?
![image](https://user-images.githubusercontent.com/35677796/222651019-54697036-79b2-4e03-8fa8-ce18d0f5e0fb.png)
If this is changed, how to synchronize to indexDb
![image](https://user-images.githubusercontent.com/35677796/222651152-088f5fb5-3e59-4630-a5cb-28a7acd49765.png)

**Comment by piotr-cz** [comment]
Cache should be updated by SWR via the `Cache.set` method, but I must admin that I didn't test such scenario.
When it doesn't I think it's a bug in SWR

**Comment by piotr-cz** [comment]
In case that you are using global mutate, it's expected to not work,

From https://swr.vercel.app/docs/advanced/cache:

> If a cache provider is used, the global mutate will not work for SWR hooks under that <SWRConfig> boundary. Please use [this](https://swr.vercel.app/docs/advanced/cache#access-current-cache-provider) instead.

**Comment by piotr-cz** [comment]
I'm closing this as completed with https://github.com/piotr-cz/swr-idb-cache/issues/6#issuecomment-1573536710

As noted in SWR docs, you can retrieve Cache provider from SWR's config and use set method
